name: PHP

on:
  workflow_call:
    inputs:
      docker-build:
        description: 'Whether the Docker image should be built and optionally published'
        default: true
        type: boolean
      docker-build-target:
        description: 'Docker target to build and optionally publish'
        default: prod
        type: string
      app-directory:
        description: 'The directory containing the app code'
        default: ./
        type: string

env:
  APP_ENV: testing

jobs:
  define:
    name: Define
    outputs:
      php_version: ${{ steps.output.outputs.php_version }}
      phpstan_level: ${{ steps.output.outputs.phpstan_level }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4

      - name: Checkout workflows repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/workflows
          path: workflows

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Output
        id: output
        run: |
          php workflows/.github/scripts/define.php ${{ inputs.app-directory }}

  pint:
    name: Laravel Pint
    runs-on: ubuntu-22.04
    needs:
      - define
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ needs.define.outputs.php_version }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          working-directory: ${{ inputs.app-directory }}

      - name: Run Laravel Pint
        working-directory: ${{ inputs.app-directory }}
        run: vendor/bin/pint --test

  phpstan:
    name: PHPStan
    runs-on: ubuntu-22.04
    needs:
      - define
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ needs.define.outputs.php_version }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          working-directory: ${{ inputs.app-directory }}

      - name: PHPStan Analyse
        working-directory: ${{ inputs.app-directory }}
        run: ./vendor/bin/phpstan analyse --level ${{ needs.define.outputs.phpstan_level }}

  docker:
    name: Docker
    if: ${{ inputs.docker-build }}
    runs-on: ubuntu-22.04
    needs:
      - pint
      - phpstan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and optionally push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
          target: ${{ inputs.docker_build_target }}